# Full spec @ https://gohugo.io/overview/configuration/
baseurl = "https://github.com/joranquinten"
languageCode = "nl-nl"
title = "Awesome title"
canonifyURLs = true

[params]
  description = "This is an awesome example of Hugo with Gulp!"

[author]
  name = "Joran Quinten"
  email = "hello@joranquinten.nl"
  about = ""